vaadin.launch-browser=true
spring.application.name=MyShopping
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Prodotti?useSSL=false&serverTimezone=UTC
spring.datasource.username=Giuseppe
spring.datasource.password=Catania1984


